version: "3.5"
services:
  mariadb:
    image: mariadb:10.5.9
    container_name: mm-wiki-db
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - mm-wiki
    ports:
      - 3306:3306
  mm-wiki:
    image: mm-wiki:v0.2
    container_name: mm-wiki
    volumes:
      - mm-wiki:/mm-wiki/data
    networks:
      - mm-wiki
    ports:
      - 8090:8090

networks:
  mm-wiki:

volumes:
  mariadb:
  mm-wiki:
